export {
  PAGE_BALANCED_STAGE_CLASS,
  PAGE_BALANCED_STAGE_TRACKS_CLASS,
  PAGE_BALANCED_STAGE_WITH_TRACKS_CLASS,
  DOC_PAGE_INLINE_OUTLINE_CLASS,
  DOC_PAGE_MAIN_CLASS,
  DOC_PAGE_RAIL_CLASS,
  DOC_PAGE_RAIL_INNER_CLASS,
  DocumentFrame,
  type DocumentOutlineMode,
  OUTLINE_RAIL_MEDIA_QUERY,
  PAGE_CONTENT_COLUMN_CLASS,
  PAGE_ICON_ROW_CLASS,
  PAGE_SHELL_CLASS,
  PAGE_STAGE_CLASS,
  PAGE_STAGE_TRACKS_CLASS,
  PAGE_STAGE_WITH_TRACKS_CLASS,
} from "@/shared/editor/components/document-layout";

export const CANVAS_PAGE_BODY_CENTERED_CLASS = "mx-auto mt-4 max-w-3xl xl:max-w-[60rem]";
export const CANVAS_PAGE_BODY_STAGE_CLASS = "mt-4 w-full";
export type CanvasStageLayout = "centered" | "stage";
